package main

import (
	"fmt"
	"math/rand"
	"os"
	"strconv"
	"time"
)

const usage = `
You have to guess the number which is randomly generated by computer
Try to guess in less number of attempt
you have to choose [Max Turn] [number between 1-100]
`

func main() {
	rand.Seed(time.Now().UnixNano())

	args := os.Args[1:]
	if len(args) != 2 {
		fmt.Printf("%s", usage)
		return
	}

	guess, errN := strconv.Atoi(args[1])
	maxTurns, errT := strconv.Atoi(args[0])

	if errT != nil || errN != nil {
		fmt.Println("Not a Number")
		return
	}

	if guess < 0 || maxTurns < 0 {
		fmt.Println("Please guess the Positive number")
		return
	}

	for turn := 0; turn < maxTurns; turn++ {
		n := rand.Intn(101)
		println(n, guess)
		if n == guess {
			fmt.Println("🎉  YOU WIN!")
			return
		}
	}

	fmt.Println("☠️  YOU LOST... Try again?")

}
